{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) -}}
{{- if or .Values.podDisruptionBudget.minAvailable .Values.podDisruptionBudget.maxUnavailable -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mica.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mica.labels" . | nindent 4 }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mica.selectorLabels" . | nindent 6 }}
{{- end -}}
{{- end -}}
